-- ⚠️ DANGER: THIS SCRIPT DELETES ALL DATA AND REBUILDS THE DATABASE ⚠️
-- Run this in Supabase SQL Editor to get a Fresh, Secure Start.

-- ==========================================
-- 1. DROP EXISTING TABLES & VIEWS
-- ==========================================
DROP VIEW IF EXISTS monthly_stats_view;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS inventory_logs CASCADE;
DROP TABLE IF EXISTS inventory_items CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS services CASCADE;

-- ==========================================
-- 2. CREATE TABLES (With RLS Built-in)
-- ==========================================

-- A. Table: SERVICES
CREATE TABLE services (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID DEFAULT auth.uid() NOT NULL, -- Auto-assigns logged in user
    name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    unit TEXT NOT NULL DEFAULT 'kg',
    category TEXT NOT NULL DEFAULT 'Cuci Komplit',
    image_url TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- B. Table: ORDERS
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID DEFAULT auth.uid() NOT NULL,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, processing, completed, paid
    total_price NUMERIC NOT NULL DEFAULT 0,
    items JSONB DEFAULT '[]'::jsonb, -- Legacy support for UI
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- C. Table: ORDER_ITEMS (Relational)
CREATE TABLE order_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    service_name TEXT NOT NULL, -- Snapshot of service name
    service_price NUMERIC NOT NULL DEFAULT 0, -- Snapshot of price
    quantity NUMERIC NOT NULL DEFAULT 1,
    unit TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- D. Table: INVENTORY_ITEMS
CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID DEFAULT auth.uid() NOT NULL,
    name TEXT NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    unit TEXT NOT NULL,
    min_stock INT DEFAULT 5,
    category TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- E. Table: INVENTORY_LOGS
CREATE TABLE inventory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID DEFAULT auth.uid() NOT NULL,
    inventory_item_id BIGINT REFERENCES inventory_items(id) ON DELETE CASCADE,
    change_amount INT NOT NULL,
    final_stock INT NOT NULL,
    change_type TEXT NOT NULL, -- restock, usage, correction, initial
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- F. Table: EXPENSES
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID DEFAULT auth.uid() NOT NULL, -- Added ownership
    category TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    description TEXT,
    expense_date DATE DEFAULT CURRENT_DATE,
    payment_method TEXT DEFAULT 'Tunai',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. ENABLE SECURITY (RLS)
-- ==========================================
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 4. CREATE POLICIES (Strict Isolation)
-- ==========================================

-- Generic function for simplicity? No, let's be explicit for constraints.

-- SERVICES
CREATE POLICY "owner_all_services" ON services
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ORDERS
CREATE POLICY "owner_all_orders" ON orders
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ORDER_ITEMS (Access via Parent Order)
CREATE POLICY "owner_all_order_items" ON order_items
    FOR ALL USING (
        EXISTS ( SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid() )
    ) WITH CHECK (
        EXISTS ( SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid() )
    );

-- INVENTORY_ITEMS
CREATE POLICY "owner_all_inventory" ON inventory_items
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- INVENTORY_LOGS
CREATE POLICY "owner_all_logs" ON inventory_logs
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- EXPENSES
CREATE POLICY "owner_all_expenses" ON expenses
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ==========================================
-- 5. SECURE VIEWS
-- ==========================================
CREATE VIEW monthly_stats_view WITH (security_invoker = true) AS
SELECT
    date_trunc('month', created_at) AS month,
    COUNT(id) AS total_orders,
    SUM(total_price) AS total_revenue
FROM
    orders
GROUP BY
    date_trunc('month', created_at);

-- DONE!
